### ISSUE TITLE
Message broker API is unable to publish

### ISSUE THREAD

**Issue by rezab777** [awslabs/aws-iot-core-integration-with-nvidia-deepstream#8]
Hi, 

Although I can successfully run the Test apps 4 and 5 locally on my Jetson device and get the visual output ( video with DeepStream inference), the metadata is not being sent to the cloud, which I believe is related to this AWS package (aws_protocol_adaptor/device_client).
The specific error I get is 
`iot_tls_connect L#164 failed. mbedtls_net_connect returned 0x44`
and
`ERROR iot_tls_write L#295 failed`
`mbedtls_ssl_write returned -0x50`
`ERROR nvds_msgapi_do_work L#286 Unable to publish, error -7`

This error was observed on multiple Jetson devices so it is not an isolated incident.

**Comment by yuxiny2586** [comment]
This 0x50 seems to be a MBEDTLS_SSL_ALERT_MSG_INTERNAL_ERROR. 
https://tls.mbed.org/api/ssl_8h_source.html

Are you able to make MQTT connections successfully? Could you double check the IoT cert locations are correctly specified in config file and have the right permissions? Also make sure that the endpoint and client ID (thing name) is correct?

If all of these are confirmed, then we recommend you rebuild .so library with DEBUG level logs to find out more information. But usually, this is due to configuration errors.

**Comment by rezab777** [comment]
I double checked the configuration and it was indeed a config related (endpoint or certificates) issue ! 
Thank you for clarification.

**Comment by rezab777** [comment]
The reason I'm reopening this is that I observed the same behaviour again. What's puzzling is the inconsistency of this. 
As an example, after running the test apps 4 and 5 the first time, the error above was observed. But running the same test apps a few days later yielded no errors, ran fine and sent data to the cloud without any issues. 
Nothing was changed in between these two instances.  And then after a few days, running the same test apps yielded the above errors again.
Please let me know If I can send you any additional logs on this.

**Comment by rezab777** [comment]
Also when trying to manually build the library (step 2) , the following error arises:
make[2]: Leaving directory '/opt/nvidia/deepstream/deepstream-5.1/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls/tests'
make[2]: Entering directory '/opt/nvidia/deepstream/deepstream-5.1/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls'
make[2]: Leaving directory '/opt/nvidia/deepstream/deepstream-5.1/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls'
make[1]: Leaving directory '/opt/nvidia/deepstream/deepstream-5.1/sources/libs/aws_protocol_adaptor/aws-iot-sdk/external_libs/mbedTLS/mbedtls'
In file included from ../aws-iot-sdk/include/network_interface.h:35:0,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client.h:57,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_interface.h:55,
                 from ../aws-iot-sdk/src/aws_iot_mqtt_client.c:45:
../aws-iot-sdk/platform/linux/mbedtls/network_platform.h:18:10: fatal error: mbedtls/config.h: No such file or directory
 #include "mbedtls/config.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../aws-iot-sdk/include/network_interface.h:35:0,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client.h:57,
                 from ../aws-iot-sdk/src/aws_iot_mqtt_client_common_internal.c:43:
../aws-iot-sdk/platform/linux/mbedtls/network_platform.h:18:10: fatal error: mbedtls/config.h: No such file or directory
 #include "mbedtls/config.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../aws-iot-sdk/include/network_interface.h:35:0,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client.h:57,
                 from ../aws-iot-sdk/src/aws_iot_mqtt_client_connect.c:44:
../aws-iot-sdk/platform/linux/mbedtls/network_platform.h:18:10: fatal error: mbedtls/config.h: No such file or directory
 #include "mbedtls/config.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../aws-iot-sdk/include/network_interface.h:35:0,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client.h:57,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_interface.h:55,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_common_internal.h:51,
                 from ../aws-iot-sdk/src/aws_iot_mqtt_client_publish.c:43:
../aws-iot-sdk/platform/linux/mbedtls/network_platform.h:18:10: fatal error: mbedtls/config.h: No such file or directory
 #include "mbedtls/config.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../aws-iot-sdk/include/network_interface.h:35:0,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client.h:57,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_interface.h:55,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_common_internal.h:51,
                 from ../aws-iot-sdk/src/aws_iot_mqtt_client_subscribe.c:42:
../aws-iot-sdk/platform/linux/mbedtls/network_platform.h:18:10: fatal error: mbedtls/config.h: No such file or directory
 #include "mbedtls/config.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../aws-iot-sdk/include/network_interface.h:35:0,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client.h:57,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_interface.h:55,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_common_internal.h:51,
                 from ../aws-iot-sdk/src/aws_iot_mqtt_client_unsubscribe.c:42:
../aws-iot-sdk/platform/linux/mbedtls/network_platform.h:18:10: fatal error: mbedtls/config.h: No such file or directory
 #include "mbedtls/config.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../aws-iot-sdk/include/network_interface.h:35:0,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client.h:57,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_interface.h:55,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_common_internal.h:51,
                 from ../aws-iot-sdk/src/aws_iot_mqtt_client_yield.c:42:
../aws-iot-sdk/platform/linux/mbedtls/network_platform.h:18:10: fatal error: mbedtls/config.h: No such file or directory
 #include "mbedtls/config.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../aws-iot-sdk/include/network_interface.h:35:0,
                 from ../aws-iot-sdk/platform/linux/mbedtls/network_mbedtls_wrapper.c:25:
../aws-iot-sdk/platform/linux/mbedtls/network_platform.h:18:10: fatal error: mbedtls/config.h: No such file or directory
 #include "mbedtls/config.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../aws-iot-sdk/include/network_interface.h:35:0,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client.h:57,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_interface.h:55,
                 from ./aws_config_parser.h:23,
                 from ./aws_config_parser.c:20:
../aws-iot-sdk/platform/linux/mbedtls/network_platform.h:18:10: fatal error: mbedtls/config.h: No such file or directory
 #include "mbedtls/config.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../aws-iot-sdk/include/network_interface.h:35:0,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client.h:57,
                 from ../aws-iot-sdk/include/aws_iot_mqtt_client_interface.h:55,
                 from ./aws_nvmsgbroker.c:27:
../aws-iot-sdk/platform/linux/mbedtls/network_platform.h:18:10: fatal error: mbedtls/config.h: No such file or directory
 #include "mbedtls/config.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:105: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by rezab777** [comment]
The reason for not being able to build the library comes down to the new version of mbetls not containing the file config.h. They have apparently renamed the file in the new version.
Please specify in the doc that an older branch of mbedtls needs to be used for the Make file to work and build the library. 
I tried `git clone -b development-psa-proposed-2 https://github.com/ARMmbed/mbedtls.git` and this specific branch does contain config.h . I believe older versions do too.

**Comment by yyx2586** [comment]
Yes. I believe you have correctly identified the issue. Let me find the right version of this mbedtls and update this repository.

**Comment by RemcoGoy** [comment]
@rezab777 , what did you end up changing to get this issue fixed?
